server {
  listen ${PORT};
  root /usr/share/nginx/html;
  index index.html;
  location /images/ { expires 30d; add_header Cache-Control "public"; }
  location / { try_files $uri $uri/ /index.html; }
}
